services:
  - type: web
    name: vitalsoft
    env: python
    buildCommand:
      - pip install -r requirements.txt
    startCommand:
      - gunicorn
      - "vitalsoft.app:app"
      - "--bind=0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
